package com.lovers.common.domain;

import java.util.Date;

public class LoversSpace {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lovers_space.space_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer spaceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lovers_space.space_name
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private String spaceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lovers_space.user_id_man
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer userIdMan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lovers_space.user_id_woman
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer userIdWoman;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lovers_space.space_background
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer spaceBackground;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lovers_space.space_content
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private String spaceContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lovers_space.create_time
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lovers_space.space_id
     *
     * @return the value of lovers_space.space_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public Integer getSpaceId() {
        return spaceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lovers_space.space_id
     *
     * @param spaceId the value for lovers_space.space_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public void setSpaceId(Integer spaceId) {
        this.spaceId = spaceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lovers_space.space_name
     *
     * @return the value of lovers_space.space_name
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public String getSpaceName() {
        return spaceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lovers_space.space_name
     *
     * @param spaceName the value for lovers_space.space_name
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public void setSpaceName(String spaceName) {
        this.spaceName = spaceName == null ? null : spaceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lovers_space.user_id_man
     *
     * @return the value of lovers_space.user_id_man
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public Integer getUserIdMan() {
        return userIdMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lovers_space.user_id_man
     *
     * @param userIdMan the value for lovers_space.user_id_man
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public void setUserIdMan(Integer userIdMan) {
        this.userIdMan = userIdMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lovers_space.user_id_woman
     *
     * @return the value of lovers_space.user_id_woman
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public Integer getUserIdWoman() {
        return userIdWoman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lovers_space.user_id_woman
     *
     * @param userIdWoman the value for lovers_space.user_id_woman
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public void setUserIdWoman(Integer userIdWoman) {
        this.userIdWoman = userIdWoman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lovers_space.space_background
     *
     * @return the value of lovers_space.space_background
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public Integer getSpaceBackground() {
        return spaceBackground;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lovers_space.space_background
     *
     * @param spaceBackground the value for lovers_space.space_background
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public void setSpaceBackground(Integer spaceBackground) {
        this.spaceBackground = spaceBackground;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lovers_space.space_content
     *
     * @return the value of lovers_space.space_content
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public String getSpaceContent() {
        return spaceContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lovers_space.space_content
     *
     * @param spaceContent the value for lovers_space.space_content
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public void setSpaceContent(String spaceContent) {
        this.spaceContent = spaceContent == null ? null : spaceContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lovers_space.create_time
     *
     * @return the value of lovers_space.create_time
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lovers_space.create_time
     *
     * @param createTime the value for lovers_space.create_time
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}