package com.lovers.common.domain;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

@Data
public class LoversIncident implements Serializable {

    private static final long serialVersionUID = -172967230835439953L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lovers_incident.incident_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer incidentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lovers_incident.incident_title
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private String incidentTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lovers_incident.incident_content
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private String incidentContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lovers_incident.incident_time
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Date incidentTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lovers_incident.incident_create_time
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Date incidentCreateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lovers_incident.user_id_man
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer userIdMan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lovers_incident.user_id_woman
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer userIdWoman;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lovers_incident.user_id_create
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer userIdCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lovers_incident.incident_images
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private String incidentImages;

}