package com.lovers.common.domain;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

@Data
public class LoversSpace implements Serializable {

    private static final long serialVersionUID = 5856653028990789008L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lovers_space.space_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer spaceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lovers_space.space_name
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private String spaceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lovers_space.user_id_man
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer userIdMan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lovers_space.user_id_woman
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer userIdWoman;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lovers_space.space_background
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer spaceBackground;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lovers_space.space_content
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private String spaceContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lovers_space.create_time
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Date createTime;

}