package com.lovers.common.domain;


import lombok.Data;

import java.io.Serializable;
import java.util.Date;

@Data
public class LoversActionWorkflow implements Serializable {

    private static final long serialVersionUID = -2399216744362853818L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lovers_action_workflow.action_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer actionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lovers_action_workflow.originator_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer originatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lovers_action_workflow.originator_name
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private String originatorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lovers_action_workflow.action_start_time
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Date actionStartTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lovers_action_workflow.action_end_time
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Date actionEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lovers_action_workflow.actual_start_time
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Date actualStartTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lovers_action_workflow.actual_end_time
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Date actualEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lovers_action_workflow.action_site
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private String actionSite;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lovers_action_workflow.actual_site
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private String actualSite;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lovers_action_workflow.action_content
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private String actionContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lovers_action_workflow.actual_content
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private String actualContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lovers_action_workflow.action_outlay
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Double actionOutlay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lovers_action_workflow.actual_outlay
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Double actualOutlay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lovers_action_workflow.examine_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer examineId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lovers_action_workflow.examine_name
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private String examineName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lovers_action_workflow.examine_time
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Date examineTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lovers_action_workflow.status
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lovers_action_workflow.action_images
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private String actionImages;

}