package com.lovers.common.domain;

import java.util.Date;

public class LoversActionWorkflow {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lovers_action_workflow.action_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer actionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lovers_action_workflow.originator_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer originatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lovers_action_workflow.originator_name
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private String originatorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lovers_action_workflow.action_start_time
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Date actionStartTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lovers_action_workflow.action_end_time
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Date actionEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lovers_action_workflow.actual_start_time
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Date actualStartTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lovers_action_workflow.actual_end_time
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Date actualEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lovers_action_workflow.action_site
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private String actionSite;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lovers_action_workflow.actual_site
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private String actualSite;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lovers_action_workflow.action_content
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private String actionContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lovers_action_workflow.actual_content
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private String actualContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lovers_action_workflow.action_outlay
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Double actionOutlay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lovers_action_workflow.actual_outlay
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Double actualOutlay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lovers_action_workflow.examine_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer examineId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lovers_action_workflow.examine_name
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private String examineName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lovers_action_workflow.examine_time
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Date examineTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lovers_action_workflow.status
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lovers_action_workflow.action_images
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private String actionImages;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lovers_action_workflow.action_id
     *
     * @return the value of lovers_action_workflow.action_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public Integer getActionId() {
        return actionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lovers_action_workflow.action_id
     *
     * @param actionId the value for lovers_action_workflow.action_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public void setActionId(Integer actionId) {
        this.actionId = actionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lovers_action_workflow.originator_id
     *
     * @return the value of lovers_action_workflow.originator_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public Integer getOriginatorId() {
        return originatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lovers_action_workflow.originator_id
     *
     * @param originatorId the value for lovers_action_workflow.originator_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public void setOriginatorId(Integer originatorId) {
        this.originatorId = originatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lovers_action_workflow.originator_name
     *
     * @return the value of lovers_action_workflow.originator_name
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public String getOriginatorName() {
        return originatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lovers_action_workflow.originator_name
     *
     * @param originatorName the value for lovers_action_workflow.originator_name
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public void setOriginatorName(String originatorName) {
        this.originatorName = originatorName == null ? null : originatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lovers_action_workflow.action_start_time
     *
     * @return the value of lovers_action_workflow.action_start_time
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public Date getActionStartTime() {
        return actionStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lovers_action_workflow.action_start_time
     *
     * @param actionStartTime the value for lovers_action_workflow.action_start_time
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public void setActionStartTime(Date actionStartTime) {
        this.actionStartTime = actionStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lovers_action_workflow.action_end_time
     *
     * @return the value of lovers_action_workflow.action_end_time
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public Date getActionEndTime() {
        return actionEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lovers_action_workflow.action_end_time
     *
     * @param actionEndTime the value for lovers_action_workflow.action_end_time
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public void setActionEndTime(Date actionEndTime) {
        this.actionEndTime = actionEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lovers_action_workflow.actual_start_time
     *
     * @return the value of lovers_action_workflow.actual_start_time
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public Date getActualStartTime() {
        return actualStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lovers_action_workflow.actual_start_time
     *
     * @param actualStartTime the value for lovers_action_workflow.actual_start_time
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public void setActualStartTime(Date actualStartTime) {
        this.actualStartTime = actualStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lovers_action_workflow.actual_end_time
     *
     * @return the value of lovers_action_workflow.actual_end_time
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public Date getActualEndTime() {
        return actualEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lovers_action_workflow.actual_end_time
     *
     * @param actualEndTime the value for lovers_action_workflow.actual_end_time
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public void setActualEndTime(Date actualEndTime) {
        this.actualEndTime = actualEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lovers_action_workflow.action_site
     *
     * @return the value of lovers_action_workflow.action_site
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public String getActionSite() {
        return actionSite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lovers_action_workflow.action_site
     *
     * @param actionSite the value for lovers_action_workflow.action_site
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public void setActionSite(String actionSite) {
        this.actionSite = actionSite == null ? null : actionSite.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lovers_action_workflow.actual_site
     *
     * @return the value of lovers_action_workflow.actual_site
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public String getActualSite() {
        return actualSite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lovers_action_workflow.actual_site
     *
     * @param actualSite the value for lovers_action_workflow.actual_site
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public void setActualSite(String actualSite) {
        this.actualSite = actualSite == null ? null : actualSite.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lovers_action_workflow.action_content
     *
     * @return the value of lovers_action_workflow.action_content
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public String getActionContent() {
        return actionContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lovers_action_workflow.action_content
     *
     * @param actionContent the value for lovers_action_workflow.action_content
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public void setActionContent(String actionContent) {
        this.actionContent = actionContent == null ? null : actionContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lovers_action_workflow.actual_content
     *
     * @return the value of lovers_action_workflow.actual_content
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public String getActualContent() {
        return actualContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lovers_action_workflow.actual_content
     *
     * @param actualContent the value for lovers_action_workflow.actual_content
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public void setActualContent(String actualContent) {
        this.actualContent = actualContent == null ? null : actualContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lovers_action_workflow.action_outlay
     *
     * @return the value of lovers_action_workflow.action_outlay
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public Double getActionOutlay() {
        return actionOutlay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lovers_action_workflow.action_outlay
     *
     * @param actionOutlay the value for lovers_action_workflow.action_outlay
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public void setActionOutlay(Double actionOutlay) {
        this.actionOutlay = actionOutlay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lovers_action_workflow.actual_outlay
     *
     * @return the value of lovers_action_workflow.actual_outlay
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public Double getActualOutlay() {
        return actualOutlay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lovers_action_workflow.actual_outlay
     *
     * @param actualOutlay the value for lovers_action_workflow.actual_outlay
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public void setActualOutlay(Double actualOutlay) {
        this.actualOutlay = actualOutlay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lovers_action_workflow.examine_id
     *
     * @return the value of lovers_action_workflow.examine_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public Integer getExamineId() {
        return examineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lovers_action_workflow.examine_id
     *
     * @param examineId the value for lovers_action_workflow.examine_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public void setExamineId(Integer examineId) {
        this.examineId = examineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lovers_action_workflow.examine_name
     *
     * @return the value of lovers_action_workflow.examine_name
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public String getExamineName() {
        return examineName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lovers_action_workflow.examine_name
     *
     * @param examineName the value for lovers_action_workflow.examine_name
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public void setExamineName(String examineName) {
        this.examineName = examineName == null ? null : examineName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lovers_action_workflow.examine_time
     *
     * @return the value of lovers_action_workflow.examine_time
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public Date getExamineTime() {
        return examineTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lovers_action_workflow.examine_time
     *
     * @param examineTime the value for lovers_action_workflow.examine_time
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public void setExamineTime(Date examineTime) {
        this.examineTime = examineTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lovers_action_workflow.status
     *
     * @return the value of lovers_action_workflow.status
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lovers_action_workflow.status
     *
     * @param status the value for lovers_action_workflow.status
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lovers_action_workflow.action_images
     *
     * @return the value of lovers_action_workflow.action_images
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public String getActionImages() {
        return actionImages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lovers_action_workflow.action_images
     *
     * @param actionImages the value for lovers_action_workflow.action_images
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public void setActionImages(String actionImages) {
        this.actionImages = actionImages == null ? null : actionImages.trim();
    }
}