package com.lovers.common.domain;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

@Data
public class SysFile implements Serializable {

    private static final long serialVersionUID = -1346417552358408263L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_file.file_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer fileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_file.file_name
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private String fileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_file.file_suffix
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private String fileSuffix;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_file.file_type
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private String fileType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_file.file_full_name
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private String fileFullName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_file.for_module
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private String forModule;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_file.user_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_file.upload_time
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Date uploadTime;

}