package com.lovers.common.domain;



import lombok.Data;

import java.io.Serializable;
import java.util.Date;

@Data
public class SysUser implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.user_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.user_account
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private String userAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.password
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.user_name
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.full_name
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private String fullName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.user_bio
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private String userBio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.user_gender
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer userGender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.user_level
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer userLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.user_role
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private String userRole;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.user_email
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private String userEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.user_birthday
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Date userBirthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.user_address
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private String userAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.user_location
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private String userLocation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.user_photo
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer userPhoto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.user_state
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer userState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.create_time
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.modified_time
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Date modifiedTime;

}