package com.lovers.common.domain;

import lombok.*;

import java.io.Serializable;
import java.util.Date;

@Data
public class UserMoodRecord implements Serializable {

    private static final long serialVersionUID = -1634690466660058314L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_mood_record.record_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer recordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_mood_record.record_title
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private String recordTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_mood_record.record_images
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private String recordImages;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_mood_record.record_content
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private String recordContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_mood_record.user_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_mood_record.create_time
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_mood_record.is_hidden
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer isHidden;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_mood_record.visitor_number
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer visitorNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_mood_record.comment_number
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer commentNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_mood_record.approver_number
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer approverNumber;

    private SysUser sysUser;



}