package com.lovers.common.domain;

import java.util.Date;

public class UserPhoto {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_photo.photo_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer photoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_photo.album_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer albumId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_photo.file_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer fileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_photo.photo_position
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private String photoPosition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_photo.photo_describe
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private String photoDescribe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_photo.upload_time
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Date uploadTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_photo.user_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_photo.for_module
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private String forModule;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_photo.photo_name
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private String photoName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_photo.photo_id
     *
     * @return the value of user_photo.photo_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public Integer getPhotoId() {
        return photoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_photo.photo_id
     *
     * @param photoId the value for user_photo.photo_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public void setPhotoId(Integer photoId) {
        this.photoId = photoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_photo.album_id
     *
     * @return the value of user_photo.album_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public Integer getAlbumId() {
        return albumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_photo.album_id
     *
     * @param albumId the value for user_photo.album_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public void setAlbumId(Integer albumId) {
        this.albumId = albumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_photo.file_id
     *
     * @return the value of user_photo.file_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public Integer getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_photo.file_id
     *
     * @param fileId the value for user_photo.file_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public void setFileId(Integer fileId) {
        this.fileId = fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_photo.photo_position
     *
     * @return the value of user_photo.photo_position
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public String getPhotoPosition() {
        return photoPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_photo.photo_position
     *
     * @param photoPosition the value for user_photo.photo_position
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public void setPhotoPosition(String photoPosition) {
        this.photoPosition = photoPosition == null ? null : photoPosition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_photo.photo_describe
     *
     * @return the value of user_photo.photo_describe
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public String getPhotoDescribe() {
        return photoDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_photo.photo_describe
     *
     * @param photoDescribe the value for user_photo.photo_describe
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public void setPhotoDescribe(String photoDescribe) {
        this.photoDescribe = photoDescribe == null ? null : photoDescribe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_photo.upload_time
     *
     * @return the value of user_photo.upload_time
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public Date getUploadTime() {
        return uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_photo.upload_time
     *
     * @param uploadTime the value for user_photo.upload_time
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public void setUploadTime(Date uploadTime) {
        this.uploadTime = uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_photo.user_id
     *
     * @return the value of user_photo.user_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_photo.user_id
     *
     * @param userId the value for user_photo.user_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_photo.for_module
     *
     * @return the value of user_photo.for_module
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public String getForModule() {
        return forModule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_photo.for_module
     *
     * @param forModule the value for user_photo.for_module
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public void setForModule(String forModule) {
        this.forModule = forModule == null ? null : forModule.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_photo.photo_name
     *
     * @return the value of user_photo.photo_name
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public String getPhotoName() {
        return photoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_photo.photo_name
     *
     * @param photoName the value for user_photo.photo_name
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public void setPhotoName(String photoName) {
        this.photoName = photoName == null ? null : photoName.trim();
    }
}