package com.lovers.common.domain;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

@Data
public class UserPhotoAlbum implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_photo_album.album_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer albumId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_photo_album.album_name
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private String albumName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_photo_album.album_cover
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer albumCover;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_photo_album.album_describe
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private String albumDescribe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_photo_album.user_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_photo_album.create_time
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_photo_album.modified_time
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Date modifiedTime;

}