package com.lovers.common.domain;

import lombok.Data;

import java.io.Serializable;

@Data
public class UserFriend implements Serializable {

    private static final long serialVersionUID = 8437342470956658983L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_friend.user_friend_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer userFriendId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_friend.user_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_friend.friend_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer friendId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_friend.friend_name
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private String friendName;

}