package com.lovers.common.domain;

import java.util.Date;

public class UserPhotoAlbum {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_photo_album.album_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer albumId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_photo_album.album_name
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private String albumName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_photo_album.album_cover
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer albumCover;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_photo_album.album_describe
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private String albumDescribe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_photo_album.user_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_photo_album.create_time
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_photo_album.modified_time
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Date modifiedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_photo_album.album_id
     *
     * @return the value of user_photo_album.album_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public Integer getAlbumId() {
        return albumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_photo_album.album_id
     *
     * @param albumId the value for user_photo_album.album_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public void setAlbumId(Integer albumId) {
        this.albumId = albumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_photo_album.album_name
     *
     * @return the value of user_photo_album.album_name
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public String getAlbumName() {
        return albumName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_photo_album.album_name
     *
     * @param albumName the value for user_photo_album.album_name
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public void setAlbumName(String albumName) {
        this.albumName = albumName == null ? null : albumName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_photo_album.album_cover
     *
     * @return the value of user_photo_album.album_cover
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public Integer getAlbumCover() {
        return albumCover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_photo_album.album_cover
     *
     * @param albumCover the value for user_photo_album.album_cover
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public void setAlbumCover(Integer albumCover) {
        this.albumCover = albumCover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_photo_album.album_describe
     *
     * @return the value of user_photo_album.album_describe
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public String getAlbumDescribe() {
        return albumDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_photo_album.album_describe
     *
     * @param albumDescribe the value for user_photo_album.album_describe
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public void setAlbumDescribe(String albumDescribe) {
        this.albumDescribe = albumDescribe == null ? null : albumDescribe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_photo_album.user_id
     *
     * @return the value of user_photo_album.user_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_photo_album.user_id
     *
     * @param userId the value for user_photo_album.user_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_photo_album.create_time
     *
     * @return the value of user_photo_album.create_time
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_photo_album.create_time
     *
     * @param createTime the value for user_photo_album.create_time
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_photo_album.modified_time
     *
     * @return the value of user_photo_album.modified_time
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_photo_album.modified_time
     *
     * @param modifiedTime the value for user_photo_album.modified_time
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }
}