package com.lovers.common.domain;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

@Data
public class UserMoodComment implements Serializable {

    private static final long serialVersionUID = -5676899257461927990L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_mood_comment.comment_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer commentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_mood_comment.record_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer recordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_mood_comment.comment_content
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private String commentContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_mood_comment.user_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_mood_comment.comment_time
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Date commentTime;
}