package com.lovers.common.domain;

import java.util.Date;

public class UserMoodComment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_mood_comment.comment_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer commentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_mood_comment.record_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer recordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_mood_comment.comment_content
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private String commentContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_mood_comment.user_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_mood_comment.comment_time
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Date commentTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_mood_comment.comment_id
     *
     * @return the value of user_mood_comment.comment_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public Integer getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_mood_comment.comment_id
     *
     * @param commentId the value for user_mood_comment.comment_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_mood_comment.record_id
     *
     * @return the value of user_mood_comment.record_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public Integer getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_mood_comment.record_id
     *
     * @param recordId the value for user_mood_comment.record_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public void setRecordId(Integer recordId) {
        this.recordId = recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_mood_comment.comment_content
     *
     * @return the value of user_mood_comment.comment_content
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public String getCommentContent() {
        return commentContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_mood_comment.comment_content
     *
     * @param commentContent the value for user_mood_comment.comment_content
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public void setCommentContent(String commentContent) {
        this.commentContent = commentContent == null ? null : commentContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_mood_comment.user_id
     *
     * @return the value of user_mood_comment.user_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_mood_comment.user_id
     *
     * @param userId the value for user_mood_comment.user_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_mood_comment.comment_time
     *
     * @return the value of user_mood_comment.comment_time
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public Date getCommentTime() {
        return commentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_mood_comment.comment_time
     *
     * @param commentTime the value for user_mood_comment.comment_time
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public void setCommentTime(Date commentTime) {
        this.commentTime = commentTime;
    }
}