package com.lovers.common.domain;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

@Data
public class UserPhoto implements Serializable {

    private static final long serialVersionUID = 5195117205593784290L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_photo.photo_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer photoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_photo.album_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer albumId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_photo.file_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer fileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_photo.photo_position
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private String photoPosition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_photo.photo_describe
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private String photoDescribe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_photo.upload_time
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Date uploadTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_photo.user_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_photo.for_module
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private String forModule;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_photo.photo_name
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private String photoName;

}