package com.lovers.common.domain;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

@Data
public class WorkflowBusiness implements Serializable {

    private static final long serialVersionUID = -8971009349656236061L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workflow_business.business_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer businessId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workflow_business.workflow_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer workflowId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workflow_business.data_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer dataId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workflow_business.create_time
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workflow_business.create_user_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workflow_business.create_user_name
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private String createUserName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workflow_business.status
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer status;

}