package com.lovers.common.domain;

import lombok.Data;

import java.io.Serializable;

@Data
public class WorkflowLink implements Serializable {

    private static final long serialVersionUID = 8369100603980907867L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workflow_link.link_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer linkId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workflow_link.workflow_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer workflowId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workflow_link.link_name
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private String linkName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workflow_link.link_key
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private String linkKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workflow_link.link_pre_node
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer linkPreNode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workflow_link.link_next_node
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer linkNextNode;

}