package com.lovers.common.domain;

public class WorkflowLink {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workflow_link.link_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer linkId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workflow_link.workflow_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer workflowId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workflow_link.link_name
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private String linkName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workflow_link.link_key
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private String linkKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workflow_link.link_pre_node
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer linkPreNode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workflow_link.link_next_node
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer linkNextNode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workflow_link.link_id
     *
     * @return the value of workflow_link.link_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public Integer getLinkId() {
        return linkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workflow_link.link_id
     *
     * @param linkId the value for workflow_link.link_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public void setLinkId(Integer linkId) {
        this.linkId = linkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workflow_link.workflow_id
     *
     * @return the value of workflow_link.workflow_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public Integer getWorkflowId() {
        return workflowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workflow_link.workflow_id
     *
     * @param workflowId the value for workflow_link.workflow_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public void setWorkflowId(Integer workflowId) {
        this.workflowId = workflowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workflow_link.link_name
     *
     * @return the value of workflow_link.link_name
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public String getLinkName() {
        return linkName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workflow_link.link_name
     *
     * @param linkName the value for workflow_link.link_name
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public void setLinkName(String linkName) {
        this.linkName = linkName == null ? null : linkName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workflow_link.link_key
     *
     * @return the value of workflow_link.link_key
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public String getLinkKey() {
        return linkKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workflow_link.link_key
     *
     * @param linkKey the value for workflow_link.link_key
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public void setLinkKey(String linkKey) {
        this.linkKey = linkKey == null ? null : linkKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workflow_link.link_pre_node
     *
     * @return the value of workflow_link.link_pre_node
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public Integer getLinkPreNode() {
        return linkPreNode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workflow_link.link_pre_node
     *
     * @param linkPreNode the value for workflow_link.link_pre_node
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public void setLinkPreNode(Integer linkPreNode) {
        this.linkPreNode = linkPreNode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workflow_link.link_next_node
     *
     * @return the value of workflow_link.link_next_node
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public Integer getLinkNextNode() {
        return linkNextNode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workflow_link.link_next_node
     *
     * @param linkNextNode the value for workflow_link.link_next_node
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public void setLinkNextNode(Integer linkNextNode) {
        this.linkNextNode = linkNextNode;
    }
}