package com.lovers.common.domain;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

@Data
public class WorkflowTask implements Serializable {

    private static final long serialVersionUID = 4092783601883116773L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workflow_task.task_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workflow_task.business_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer businessId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workflow_task.start_user_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer startUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workflow_task.start_user_name
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private String startUserName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workflow_task.start_time
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workflow_task.end_user_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer endUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workflow_task.end_user_name
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private String endUserName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workflow_task.end_time
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workflow_task.node_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer nodeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workflow_task.link_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer linkId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workflow_task.status
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer status;

}