package com.lovers.common.domain;

import lombok.Data;

import java.io.Serializable;

@Data
public class WorkflowNode implements Serializable {

    private static final long serialVersionUID = -7412586896586732496L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workflow_node.node_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer nodeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workflow_node.node_key
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private String nodeKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workflow_node.workflow_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer workflowId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workflow_node.node_name
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private String nodeName;

}