package com.lovers.common.domain;

public class WorkflowNode {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workflow_node.node_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer nodeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workflow_node.node_key
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private String nodeKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workflow_node.workflow_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer workflowId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workflow_node.node_name
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private String nodeName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workflow_node.node_id
     *
     * @return the value of workflow_node.node_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public Integer getNodeId() {
        return nodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workflow_node.node_id
     *
     * @param nodeId the value for workflow_node.node_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public void setNodeId(Integer nodeId) {
        this.nodeId = nodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workflow_node.node_key
     *
     * @return the value of workflow_node.node_key
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public String getNodeKey() {
        return nodeKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workflow_node.node_key
     *
     * @param nodeKey the value for workflow_node.node_key
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public void setNodeKey(String nodeKey) {
        this.nodeKey = nodeKey == null ? null : nodeKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workflow_node.workflow_id
     *
     * @return the value of workflow_node.workflow_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public Integer getWorkflowId() {
        return workflowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workflow_node.workflow_id
     *
     * @param workflowId the value for workflow_node.workflow_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public void setWorkflowId(Integer workflowId) {
        this.workflowId = workflowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workflow_node.node_name
     *
     * @return the value of workflow_node.node_name
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public String getNodeName() {
        return nodeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workflow_node.node_name
     *
     * @param nodeName the value for workflow_node.node_name
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public void setNodeName(String nodeName) {
        this.nodeName = nodeName == null ? null : nodeName.trim();
    }
}