package com.lovers.common.domain;

import java.util.Date;

public class WorkflowBusiness {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workflow_business.business_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer businessId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workflow_business.workflow_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer workflowId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workflow_business.data_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer dataId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workflow_business.create_time
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workflow_business.create_user_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workflow_business.create_user_name
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private String createUserName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workflow_business.status
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workflow_business.business_id
     *
     * @return the value of workflow_business.business_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public Integer getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workflow_business.business_id
     *
     * @param businessId the value for workflow_business.business_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public void setBusinessId(Integer businessId) {
        this.businessId = businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workflow_business.workflow_id
     *
     * @return the value of workflow_business.workflow_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public Integer getWorkflowId() {
        return workflowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workflow_business.workflow_id
     *
     * @param workflowId the value for workflow_business.workflow_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public void setWorkflowId(Integer workflowId) {
        this.workflowId = workflowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workflow_business.data_id
     *
     * @return the value of workflow_business.data_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public Integer getDataId() {
        return dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workflow_business.data_id
     *
     * @param dataId the value for workflow_business.data_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public void setDataId(Integer dataId) {
        this.dataId = dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workflow_business.create_time
     *
     * @return the value of workflow_business.create_time
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workflow_business.create_time
     *
     * @param createTime the value for workflow_business.create_time
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workflow_business.create_user_id
     *
     * @return the value of workflow_business.create_user_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workflow_business.create_user_id
     *
     * @param createUserId the value for workflow_business.create_user_id
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workflow_business.create_user_name
     *
     * @return the value of workflow_business.create_user_name
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public String getCreateUserName() {
        return createUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workflow_business.create_user_name
     *
     * @param createUserName the value for workflow_business.create_user_name
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public void setCreateUserName(String createUserName) {
        this.createUserName = createUserName == null ? null : createUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workflow_business.status
     *
     * @return the value of workflow_business.status
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workflow_business.status
     *
     * @param status the value for workflow_business.status
     *
     * @mbg.generated Wed Sep 25 10:59:33 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}